# Licensed under the Apache-2.0 license
# SPDX-License-Identifier: Apache-2.0
"""Tool enabling agents to consult the Project Expert Agent."""

import uuid

from google.adk.tools import ToolContext

from constants import (
    PROJECT_EXPERT_QUERY_LOG_PREVIEW_CHARS,
    PROJECT_EXPERT_QUERY_PROMPT_TEMPLATE,
)
from providers.adk.agents.project_expert import get_project_expert_agent
from providers.adk.utilities.async_runner import extract_agent_text, run_agent_node
from utilities.decorators import limit_tool_output
from utilities.logger import logger


@limit_tool_output
async def ask_project_expert(
    question: str,
    tool_context: ToolContext | None = None,
) -> str:
    """Consults the Project Expert Agent for project-level architectural guidance, design rationale,

    subsystem boundaries, or hardware/firmware interface conventions. Use this tool when you need
    clarification on whether a behavior is intentional, how components interact, or what the threat
    model dictates for a specific component.

    Args:
        question: The specific technical or architectural question about the project.

    Returns:
        The Project Expert's answer grounded in the project codebase and threat model.
    """
    if not tool_context or not tool_context.state:
        return "Error: ToolContext not available to access Project Expert."

    state = tool_context.state
    model = state.get("model")
    threat_model = state.get("threat_model_context", "")
    summary = state.get("project_expert_summary", "")
    qa_history: list[dict[str, str]] = list(state.get("project_expert_qa_history", []))

    normalized_question = " ".join(question.strip().lower().split())
    for item in qa_history:
        if " ".join(item.get("question", "").strip().lower().split()) == normalized_question:
            logger.debug("[Tool Execution] ask_project_expert: returning cached Q&A hit.")
            return item["answer"]

    if not model:
        if summary:
            return f"Project Expert Agent not actively loaded. Here is the initial exploration summary:\n\n{summary}"
        return "Project Expert Agent is not available in the current session."

    preview = question[:PROJECT_EXPERT_QUERY_LOG_PREVIEW_CHARS]
    logger.debug(f"[Tool Execution] ask_project_expert: {preview}...")

    project_expert_agent = get_project_expert_agent(
        model=model,
        threat_model_context=threat_model,
        project_summary=summary,
        qa_history=qa_history,
    )
    query_input = PROJECT_EXPERT_QUERY_PROMPT_TEMPLATE.format(question=question)

    try:
        res = await run_agent_node(
            tool_context,
            project_expert_agent,
            node_input=query_input,
            run_id=f"expert_query_{uuid.uuid4().hex[:8]}",
        )
    except Exception as e:
        logger.warning(f"Error querying Project Expert Agent: {e}")
        if summary:
            return (
                f"Error querying Project Expert Agent ({e}). "
                f"Falling back to initial exploration summary:\n\n{summary}"
            )
        return f"Error querying Project Expert Agent: {e}"

    answer = extract_agent_text(res, default="")
    if not answer:
        return "No response generated by Project Expert."

    updated_history = list(state.get("project_expert_qa_history", []))
    updated_history.append({"question": question.strip(), "answer": answer})
    state["project_expert_qa_history"] = updated_history
    return answer
