name: Lint

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.19.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Format Check
        run: bazel test //quality:format_check

      - name: License Header Check
        run: bazel test //quality:license_check

      - name: Shell Script Check
        run: bazel test //quality:shellcheck
